# 修改此配置后，需同步更新SimpleProtoConfig的初始化方法
simpleproto:
  # 数据库连接配置(PostgreSQL、）
  dataSourceDriver: org.postgresql.Driver
  dataSourceUrl: jdbc:postgresql://42.192.108.249:5432/${spring.application.name}?currentSchema=${spring.profiles.active}&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  dataSourceUsername: postgres
  dataSourcePassword: Wanfeng730
  # OpenSearch 连接配置
  opensearchHostScheme: http
  opensearchHost: 42.192.108.249
  opensearchPort: 9200
  opensearchUsername: admin
  opensearchPassword: Wanfeng730
  # OpenSearch jdbc配置
  opensearchJdbcDriver: com.amazon.opendistroforelasticsearch.jdbc.Driver
  opensearchJdbcUrl: jdbc:elasticsearch://http://42.192.108.249:9200
  opensearchJdbcUseSSL: false
  # Redis连接配置
  redisHost: 42.192.108.249
  redisPort: 6379
  redisPassword: Wanfeng730
  redisDatabase: 0
  # 数据库名称取spring应用名称
  currentScheme: ${spring.profiles.active}
  # 业务数据表名
  dataTable: xhs_data
  # 业务设置表名
  settingsTable: xhs_settings

######################################################
server:
  servlet:
    context-path: /xhs

spring:
  application:
    name: xhs
  profiles:
    active: dev
  # Postgres数据源
  datasource:
    postgres:
      driver-class-name: ${simpleproto.dataSourceDriver}
      url: ${simpleproto.dataSourceUrl}
      username: ${simpleproto.dataSourceUsername}
      password: ${simpleproto.dataSourcePassword}
    search:
      driver-class-name: ${simpleproto.opensearchJdbcDriver}
      url: ${simpleproto.opensearchJdbcUrl}
      username: ${simpleproto.opensearchUsername}
      password: ${simpleproto.opensearchPassword}
      useSSL: ${simpleproto.opensearchJdbcUseSSL}
  data:
    redis:
      host: ${simpleproto.redisHost}
      port: ${simpleproto.redisPort}
      password: ${simpleproto.redisPassword}
      database: ${simpleproto.redisDatabase}
  # 数据库连接方言配置
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
  # 全局json日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # ElasticSearch数据源
  elasticsearch:
    uris: ${simpleproto.esUris}
    username: ${simpleproto.esUsername}
    password: ${simpleproto.esPassword}

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
  # mapper xml文件扫描路径
  mapper-locations: classpath:mapper/postgres/*Mapper.xml

# 日志配置
logging:
  file:
    path: ./logs
  level:
    root: info
    org.springframework.boot: warn
    org.springframework.web: warn
    cn.wanfeng.xhs.article.mapper.search: debug



